package school;

public enum EnumSoft {
    TANGTHEOTEN,
    GIAMTHEOTEN,
    TANGTHEOHOTEN,
    GIAMTHEOHOTEN,
    TANGTHEOTUOI,
    GIAMTHEOTUOI,
    TANGTHEOCHIEUCAO,
    GIAMTHEOCHIEUCAO,
    TANGTHEOCANNANG,
    GIAMTHEOCANNANG,
    TANGTHEOTINCHI,
    GIAMTHEOTINCHI,
    TANGTHEONAMSINH,
    GIAMTHEONAMSINH,
    
   
}
